PADV 1126 - lock the username column when scrolling to the right
Pearson-Advance/frontend-app-gradebook pull request #1
Opened 2024-04-02 16:38 UTC by alexjmpb

## Ticket

https://agile-jira.pearson.com/browse/PADV-1126

## Description

This PR aims to lock the username column and the header when scrolling through the gradebook table. The approach take was to do the functionality with CSS since the DataTable component from Paragon didn't have an option to lock a column.

## Screenshots

[Screencast from 02-04-24 11:36:35.webm](https://github.com/Pearson-Advance/frontend-app-gradebook/assets/62396424/73d97022-e952-490a-9993-58e1719bffaa)

## How to test?

- Setup devstack
- Add to gradebook repo this remote and checkout to this branch.
- Create a graded course with enough assignments for the scroll to appear.
- Verify that the username column and the header are locked when scrolling.

2024-04-02 16:55 UTC, AuraAlba approved these changes

2024-04-04 11:35 UTC, Squirrel18 requested changes

2024-04-04 11:35 UTC, Squirrel18 commented on src/components/GradesView/GradesView.scss
> +// These overflow configs are needed for the sticky to work
```suggestion
// Table First column and Header fixer.

// These overflow configs are needed for the sticky to work.
```

2024-04-04 11:35 UTC, Squirrel18 commented on src/components/GradesView/GradesView.scss
> +  background-color: rgb(251, 250, 249);
Can we get this color from a variable definition? @alexjmpb Is there already available in other modules?

2024-04-04 14:58 UTC, Squirrel18 approved these changes

2024-04-04 15:56 UTC, merged